### PR TITLE
Fix the typo and support browserify.

### PR DESCRIPTION
**Pull request by jessy1092**
- It has error when use. It cannot found the nodule because of typo.
- Add config to support browserify.

Signed-off-by: Lee <jessy1092@gmail.com>

### CODE REVIEW

**Comment by akiran** [comment]
@jessy1092 It is not a typo.  Since react component uses jsx I used jsx extension.

You should be able use it with browserify 
```bash
browserify --extension=.jsx -t [ reactify ] app.jsx > bundle.js
```
Checkout this link
https://github.com/andreypopp/reactify/issues/12

**Comment by jessy1092** [comment]
I use package.json config the browserify. It would be passed when I add this commit.

Anyway, I use command.
`browserify --extension=.jsx -t [ reactify ] app.jsx > bundle.js`

It occurs

`Error: Parsing file c:\Users\Lee\workspace_react\react-example\node_modules\react-highlight\index.jsx: Unexpected token (29:8)`

If I use code.

```ls
  b = browserify {extensions: [".jsx"]}
  b.add './client/scripts/index.js'
    .transform reactifyES6
    .bundle!
    .pipe source 'bundle.js'
    .pipe buffer!
    .pipe uglify!
    .pipe gulp.dest "#{build_path}/scripts/"
```

It has the same problem.

**Comment by akiran** [comment]
Is it working If we change from
` main: index.jsx`
to 
`main: index.js`

**Comment by akiran** [comment]
@jessy1092 Thanks for the pull request.

I mostly use webpack.
I didn't know that we have to add 
 "browserify": {
    "transform": "reactify"
}
in dependency package.json to support browserify.
I thought it is sufficient to add it root package.

**Comment by jessy1092** [comment]
Yes, we need add `"browserify": { "transform": "reactify" }` if this module would be used in another project. :)
See this https://github.com/andreypopp/reactify/issues/20

**Pull request merged**
